server:
      port: 8091
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        hikari:
            connectionTimeout: 30000
            idleTimeout: 30000
            maxLifetime: 2000000
            maximumPoolSize: 10
            minimumIdle: 5
            poolName: HikariPoolTest
        password: mms
        url: jdbc:oracle:thin:@10.22.7.63:1521/GTGTTEST
        username: MMS
    jpa:
        database-platform: org.hibernate.dialect.Oracle12cDialect
        hibernate:
            ddl-auto: create
        show-sql: true
    rabbitmq:
        host: 10.22.7.88
        port: 6789
        username: qrcode
        password: qrcode
        requested-heartbeat: 45
        virtual-host: qrcode
        listener:
            simple:
                concurrency: 1
                max-concurrency: 10
                prefetch: 1
                auto-startup: true
                default-requeue-rejected: true
        publisher-returns: true
        connection-timeout: 10000
    cache:
        type: redis
    redis:
        host: 10.22.7.111
        port: 6379
        password: testredis@123
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 5
                max-wait: -1
        timeout: 1
        connect-timeout: 10000
        database: 5
        sentinel:
            nodes: 10.22.7.112:6379
            password: testredis@123