server:
      port: 8090
spring:
    rabbitmq:
        host: 10.22.7.88
        port: 6789
        username: qrcode
        password: qrcode
        requested-heartbeat: 45
        virtual-host: qrcode
        listener:
            simple:
                concurrency: 10
                max-concurrency: 10
                prefetch: 1
                auto-startup: true
                default-requeue-rejected: true
        publisher-returns: true
        connection-timeout: 10000
    cache:
        type: redis
    redis:
        host: 10.22.7.111
        port: 6379
        password: testredis@123
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 5
                max-wait: -1
        timeout: 3
        connect-timeout: 10000
        database: 5
        sentinel:
            nodes: 10.22.7.112:6379
            password: testredis@123